### ISSUE TITLE
error loading the script on ES-DE

### ISSUE THREAD

**Issue by informadortech** [GlazedBelmont/es-de-android-batocera-systems#1]
After placing the script ES-DE fails to load due a type error:

there is no starting system tag before astrocde

easy fix though. Thanks for your work

![image](https://github.com/user-attachments/assets/aa281ab9-ab99-4004-a529-bbe462f79fbe)

**Comment by GlazedBelmont** [comment]
https://github.com/GlazedBelmont/es-de-android-batocera-systems/commit/d9426db9af3ee0a2d7ae22f984d06eafb26d8b0b
